
- name: install ruby dependencies
  command: bash -lc 'bundle install' chdir={{ base_path }}
  sudo_user: vagrant

- name: install nodejs dependencies (package.json)
  npm: path={{ base_path }}/public

- name: set shell locale encoding
  lineinfile: dest={{ bashrc_path }} line='export LC_ALL=en_US.UTF-8' insertafter='EOF' regexp='export LC_ALL=en_US.UTF-8' state=present

- name: declares GOOGLE_API_CLIENT
  lineinfile: dest={{ bashrc_path }} line='export GOOGLE_API_CLIENT={{ lookup("env", "GOOGLE_API_CLIENT") }}' insertafter='EOF' regexp='export GOOGLE_API_CLIENT' state=present

- name: declares GOOGLE_API_SECRET
  lineinfile: dest={{ bashrc_path }} line='export GOOGLE_API_SECRET={{ lookup("env", "GOOGLE_API_SECRET") }}' insertafter='EOF' regexp='export GOOGLE_API_SECRET' state=present

- name: declares GOOGLE_API_KEY
  lineinfile: dest={{ bashrc_path }} line='export GOOGLE_API_KEY={{ lookup("env", "GOOGLE_API_KEY") }}' insertafter='EOF' regexp='export GOOGLE_API_KEY' state=present

- name: declares JIGSAW_API_SECRET
  lineinfile: dest={{ bashrc_path }} line='export JIGSAW_API_SECRET={{ lookup("env", "JIGSAW_API_SECRET") }}' insertafter='EOF' regexp='export JIGSAW_API_SECRET' state=present

- name: declares REDIS_PASSWORD
  lineinfile: dest={{ bashrc_path }} line='export REDIS_PASSWORD={{ lookup("env", "REDIS_PASSWORD") }}' insertafter='EOF' regexp='export REDIS_PASSWORD' state=present

- name: declares REDIS_URL
  lineinfile: dest={{ bashrc_path }} line='export REDIS_URL={{ lookup("env", "REDIS_URL") }}' insertafter='EOF' regexp='export REDIS_URL' state=present

- name: populate REDIS_URL
  command: bash -lc '/vagrant/agendador/bin/sync_with_jigsaw'
  environment:
    REDIS_URL: '{{ lookup("env", "REDIS_URL") }}'
    JIGSAW_API_SECRET: '{{ lookup("env", "JIGSAW_API_SECRET") }}'
  sudo_user: vagrant
