
- name: install ruby dependencies
  command: bash -lc 'bundle install' chdir={{ base_path }}
  sudo_user: vagrant

- name: install nodejs dependencies (package.json)
  npm: path={{ base_path }}/public

- name: set shell locale
  lineinfile: dest={{ bashrc_path }} line='export LC_ALL=en_US.UTF-8' insertafter='EOF' regexp='export LC_ALL=en_US.UTF-8' state=present

- name: set shell language
  lineinfile: dest={{ bashrc_path }} line='export LANG=en_US.UTF-8' insertafter='EOF' regexp='export LANG=en_US.UTF-8' state=present

- name: declares GOOGLE_API_CLIENT
  lineinfile: dest={{ bashrc_path }} line='export GOOGLE_API_CLIENT=your_client_id' insertafter='EOF' regexp='export GOOGLE_API_CLIENT' state=present

- name: declares GOOGLE_API_SECRET
  lineinfile: dest={{ bashrc_path }} line='export GOOGLE_API_SECRET=your_secret' insertafter='EOF' regexp='export GOOGLE_API_SECRET' state=present

- name: declares GOOGLE_API_KEY
  lineinfile: dest={{ bashrc_path }} line='export GOOGLE_API_KEY=your_key' insertafter='EOF' regexp='export GOOGLE_API_KEY' state=present

- name: declares JIGSAW_API_SECRET
  lineinfile: dest={{ bashrc_path }} line='export JIGSAW_API_SECRET=your_secret' insertafter='EOF' regexp='export JIGSAW_API_SECRET' state=present

- name: declares SAML_ISSUER
  lineinfile: dest={{ bashrc_path }} line="export SAML_ISSUER='{{ default_saml_issuer }}'" insertafter='EOF' regexp='export SAML_ISSUER' state=present

- name: declares SAML_TARGET_URL
  lineinfile: dest={{ bashrc_path }} line="export SAML_TARGET_URL={{ default_saml_target_url }}" insertafter='EOF' regexp='export SAML_TARGET_URL' state=present

- name: declares SAML_FINGERPRINT
  lineinfile: dest={{ bashrc_path }} line='export SAML_FINGERPRINT=your_fingerprint' insertafter='EOF' regexp='export SAML_FINGERPRINT' state=present
