
- name: install ruby dependencies
  command: bash -lc 'bundle install' chdir={{ base_path }}
  sudo_user: vagrant

- name: install nodejs dependencies (package.json)
  npm: path={{ base_path }}/public

- name: Adding the path in the bashrc files
  lineinfile: dest=/home/vagrant/.bashrc line='export LC_ALL=en_US.UTF-8' insertafter='EOF' regexp='export LC_ALL=en_US.UTF-8' state=present

- name: Adding the path in the bashrc files
  lineinfile: dest=/home/vagrant/.bashrc line='export LANG=en_US.UTF-8' insertafter='EOF' regexp='export LANG=en_US.UTF-8' state=present

- name: Adding the G_API_CLIENT the bashrc files
  lineinfile: dest=/home/vagrant/.bashrc line='export G_API_CLIENT=your_client_id' insertafter='EOF' regexp='export G_API_CLIENT' state=present

- name: Adding the G_API_SECRET the bashrc files
  lineinfile: dest=/home/vagrant/.bashrc line='export G_API_SECRET=your_secret' insertafter='EOF' regexp='export G_API_SECRET' state=present

- name: Adding the G_API_KEY the bashrc files
  lineinfile: dest=/home/vagrant/.bashrc line='export G_API_KEY=your_api_key' insertafter='EOF' regexp='export G_API_KEY' state=present
