var url = 'https://accounts.google.com/o/oauth2/auth',
    response_type = 'token',
    client_id = '',
    redirect_uri = '',
    scope = '',
    state = '',
    approval_prompt = '',
    login_hint = '',
    include_granted_scopes = '';
